/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MyRecipesIndexImport } from './routes/my-recipes/index'
import { Route as CreateRecipeIndexImport } from './routes/create-recipe/index'
import { Route as RecipeIdIndexImport } from './routes/recipe/$id/index'
import { Route as RecipeIdEditIndexImport } from './routes/recipe/$id/edit/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MyRecipesIndexRoute = MyRecipesIndexImport.update({
  id: '/my-recipes/',
  path: '/my-recipes/',
  getParentRoute: () => rootRoute,
} as any)

const CreateRecipeIndexRoute = CreateRecipeIndexImport.update({
  id: '/create-recipe/',
  path: '/create-recipe/',
  getParentRoute: () => rootRoute,
} as any)

const RecipeIdIndexRoute = RecipeIdIndexImport.update({
  id: '/recipe/$id/',
  path: '/recipe/$id/',
  getParentRoute: () => rootRoute,
} as any)

const RecipeIdEditIndexRoute = RecipeIdEditIndexImport.update({
  id: '/recipe/$id/edit/',
  path: '/recipe/$id/edit/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-recipe/': {
      id: '/create-recipe/'
      path: '/create-recipe'
      fullPath: '/create-recipe'
      preLoaderRoute: typeof CreateRecipeIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-recipes/': {
      id: '/my-recipes/'
      path: '/my-recipes'
      fullPath: '/my-recipes'
      preLoaderRoute: typeof MyRecipesIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$id/': {
      id: '/recipe/$id/'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$id/edit/': {
      id: '/recipe/$id/edit/'
      path: '/recipe/$id/edit'
      fullPath: '/recipe/$id/edit'
      preLoaderRoute: typeof RecipeIdEditIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-recipe': typeof CreateRecipeIndexRoute
  '/my-recipes': typeof MyRecipesIndexRoute
  '/recipe/$id': typeof RecipeIdIndexRoute
  '/recipe/$id/edit': typeof RecipeIdEditIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-recipe': typeof CreateRecipeIndexRoute
  '/my-recipes': typeof MyRecipesIndexRoute
  '/recipe/$id': typeof RecipeIdIndexRoute
  '/recipe/$id/edit': typeof RecipeIdEditIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-recipe/': typeof CreateRecipeIndexRoute
  '/my-recipes/': typeof MyRecipesIndexRoute
  '/recipe/$id/': typeof RecipeIdIndexRoute
  '/recipe/$id/edit/': typeof RecipeIdEditIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-recipe'
    | '/my-recipes'
    | '/recipe/$id'
    | '/recipe/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-recipe'
    | '/my-recipes'
    | '/recipe/$id'
    | '/recipe/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/create-recipe/'
    | '/my-recipes/'
    | '/recipe/$id/'
    | '/recipe/$id/edit/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRecipeIndexRoute: typeof CreateRecipeIndexRoute
  MyRecipesIndexRoute: typeof MyRecipesIndexRoute
  RecipeIdIndexRoute: typeof RecipeIdIndexRoute
  RecipeIdEditIndexRoute: typeof RecipeIdEditIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRecipeIndexRoute: CreateRecipeIndexRoute,
  MyRecipesIndexRoute: MyRecipesIndexRoute,
  RecipeIdIndexRoute: RecipeIdIndexRoute,
  RecipeIdEditIndexRoute: RecipeIdEditIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-recipe/",
        "/my-recipes/",
        "/recipe/$id/",
        "/recipe/$id/edit/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-recipe/": {
      "filePath": "create-recipe/index.tsx"
    },
    "/my-recipes/": {
      "filePath": "my-recipes/index.tsx"
    },
    "/recipe/$id/": {
      "filePath": "recipe/$id/index.tsx"
    },
    "/recipe/$id/edit/": {
      "filePath": "recipe/$id/edit/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
